### ISSUE TITLE
works with xterm

### ISSUE THREAD

**Issue by eylles** [intrntbrn/awesomewm-vim-tmux-navigator#1]
tho there's some jank, so instead of outright saying it doesn't warn that there's minor jank to be expected, otherwise this is great

**Comment by intrntbrn** [comment]
Can you share your xterm config? I couldn't get it to work.

**Comment by eylles** [comment]
no prob, i use uxterm cuz i'm too lazy to set the utf8 mode in xterm properly so just remove the `U` for xterm:
```! text font
UXTerm*faceName: BlexMono NF:style=Regular:size=9
! font unreadable
UXTerm*faceSize1: 3
! do not compare bold to normal font
UXTerm*freeBoldBox: true
! set saved lines
UXTerm*saveLines: 99999
! send events
UXTerm.allowSendEvents: true
! double-click to select whole URLs :D
UXTerm*charClass: 33:48,36-47:48,58-59:48,61:48,63-64:48,95:48,126:48
! Allow sixel graphics. (Try: "convert -colors 16 foo.jpg sixel:-").
UXTerm*decTerminalID : vt340
! alt is escape
UXTerm.vt100.allowTitleOps: true
UXTerm.vt100.metaSendsEscape: true
UXTerm.vt100.internalBorder: 4
! cursor
UXTerm*selectToClipboard: true
! keybind overrides
UXTerm*VT100.Translations: #override \n\
    Ctrl <Key> -: smaller-vt-font() \n\
    Ctrl <Key> +: larger-vt-font() \n\
    Ctrl <Key> 0: set-vt-font(d) \n\
    Shift Ctrl <Key>T: spawn-new-terminal() \n\
    <BtnUp>:select-end(SELECT, CUT_BUFFER0, PRIMARY) \n\
    Shift Ctrl <Key>B: set-scrollbar(toggle) \n\
    Ctrl Shift <Key>H: set-altscreen(toggle) \n\
    Shift <KeyPress> Home : scroll-to(begin) \n\
    Shift <KeyPress> End  : scroll-to(end) \n\
    Shift <KeyPress> Insert: insert-selection(CLIPBOARD) \n\
    Ctrl Shift <Key>V:    insert-selection(CLIPBOARD) \n\
    Ctrl Shift <Key>C:    copy-selection(CLIPBOARD) \n\
    Ctrl <Btn1Up>: exec-formatted("xdg-open '%t'", PRIMARY)
```
tho it could be the version of xterm, i use devuan ceres (equivalent to debian sid) and xterm 366, tho back when i was using ubuntu 20.04 never saw xterm (uxterm for that matter) change title only saw it when i switched to devuan ceres and ran pulsemixer on uxterm, so it may be something that got added to the late 2020 releases of xterm.

in regards of the jank lets say i have 2 xterm windows tiled side by side, and i open tmux on the left one, then in tmux i split my window horizontally, i hit modkey+h to go to the left pane and the focus switches to the left pane, then hit modkey+l and the focus switches over the right xterm window, it ignores the right tmux pane, if i understand correctly the expected behaviour would be that modkey+l would switch over the right tmux pane wouldn't it?

anyway that jank aside this module is awesome! 👍

**Comment by intrntbrn** [comment]
I've tried your config in latest xterm (compiled git) and it still doesn't work for me.

Regarding your tiling issue: If i understand the scenario correctly, it should work without any issues.

![navigator](https://user-images.githubusercontent.com/1234183/111380853-2f867980-86a5-11eb-8557-527bf1f80895.gif)

What doesn't work properly is when pane 1 is selected in tmux, windows 3 has focus and you are navigating left. This will focus pane 1 (and skip 2). This is not an easy fix unfortunately.

![wrong](https://user-images.githubusercontent.com/1234183/111381392-f4387a80-86a5-11eb-93e9-7e26602576f6.gif)

**Comment by eylles** [comment]
ah i forgot to mention i use zsh and i did add the functions for zsh
in this gif all the movements were with modkey+h and modkey+l
![recorded](https://user-images.githubusercontent.com/33670677/111393805-18349580-867f-11eb-8d65-00c8f9ec2699.gif)

also the config i gave was for xterm started as uxterm, the one option that matters is ```XTerm.vt100.allowTitleOps: true```

**Comment by intrntbrn** [comment]
This isn't supposed to happen. 
Please run `tmux display-message -p '#{pane_at_right}'` on the left pane. It should return `0` otherwise there is something wrong with your tmux configuration.

To debug this, have a look at `tmux_focus.sh`.

**Comment by eylles** [comment]
`tmux display-message -p '#{pane_at_right}'` returned 0

any advice for debugging?

**Comment by intrntbrn** [comment]
If it's 0 then `tmux_focus.sh` should have selected the right pane instead of the right window.

```if [ "$(tmux display-message -p '#{pane_at_right}')" -ne 1 ]; then tmux select-pane -R; else wm_focus; fi ;;```

Honestly, i have no clue how this could fail.

To debug it, walk along the whole chain: 
1. `init.lua` is being called when you press your awesomewm navigation keybinds.
2. Because the title of the window matches "- TMUX$", it will send Ctrl-Right to tmux.
3. Ctrl-Right will call `tmux_focus.sh`. It will check if there is another pane to the right. This is the case when `tmux display-message -p '#{pane_at_right}')"` returns != 1. The script will then send `tmux select-pane -R`. Otherwise awesomewm will focus the window to the right.

**Comment by eylles** [comment]
ah wait, i'm dumb, it happened because i already had keybinds to move by direction in rc.lua, these ones
```lua
    awful.key({ modkey }, "j", function() awful.client.focus.bydirection("down")  end,
              {description = "focus window down", group = "client"}),
    awful.key({ modkey }, "k", function() awful.client.focus.bydirection("up")    end,
              {description = "focus window up", group = "client"}),
    awful.key({ modkey }, "h", function() awful.client.focus.bydirection("left")  end,
              {description = "focus window left", group = "client"}),
    awful.key({ modkey }, "l", function() awful.client.focus.bydirection("right") end,
              {description = "focus window right", group = "client"}),
```
removed them but left the keybinds to swap windows by direction and now it works as intended

it would be a nice idea to warn in the readme about bindings like these that will conflict with the bindings set by the module

**Comment by intrntbrn** [comment]
It's already there in the readme: "Remove conflicting keybinds from your rc.lua.". 

Adding the warning is all i can do since removing already existing keybinds isn't working properly atm.

All good now?

**Comment by eylles** [comment]
lol, i totally skipped that, didn't read past how to require the module, but yes all is good now
